claim-start-message: Test1
claim-cannot-complete-message: Test2
claim-left-click-corner-message: Test3
claim-right-click-corner-message: Test4
claim-completed-message: Test5
claim-inventory-title: claim-inventory-title
claim-information-item-name: claim-information-item-name
claim-information-item-lore: [claim-information-item-lore, "%OWNER%%VOLUME%%AREA%%COORD1%%COORD2%"]
claim-view-item-name: claim-view-item-name
claim-view-item-lore: claim-view-item-lore
claim-members-item-name: claim-members-item-name
claim-members-item-lore: claim-members-item-lore
claim-flags-item-name: claim-flags-item-name
claim-flags-item-lore: claim-flags-item-lore
claim-delete-item-name: claim-delete-item-name
claim-delete-item-lore: claim-delete-item-lore
members-inventory-title: members-inventory-title
go-back-to-menu-item-name: go-back-to-menu-item-name
go-back-to-menu-item-lore: go-back-to-menu-item-lore
add-member-item-name: add-member-item-name
add-member-item-lore: add-member-item-lore
member-head-lore: [ member-head-lore , Left-click to remove member ]
boss-bar-text: "&bYou have %TIME_LEFT% left of flight!"
not-enough-money-error: "&cYou don't have enough money! You need %NEED% and you have %HAVE%"
price-per-block: 50