name: Claims
main: com.github.mrgeotech.Claims
version: 1.0
author: MrGeoTech
api-version: 1.18

commands:
  flyclaim:
    permission: claim.fly
    usage: "Usage: /flyclaim <user> minutes>"
  claim:
    usage: "Usage: /claim"